// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RawrAutoCompactionJudgmentResultEvent = { 
/**
 * Correlates this result event with the originating request.
 */
request_id: string, 
/**
 * Tier name (`early`/`ready`/`asap`/`emergency`).
 */
tier: string, should_compact: boolean, reason: string, };
